### ISSUE TITLE
Open-source the server side

### ISSUE THREAD

**Issue by CrazyPython** [Matheus28/m28n-cli#4]

**Comment by Matheus28** [comment]
No

**Comment by CrazyPython** [comment]
I am a former co-dev of Arras and am now developing a sequel to Arras with my fellow Arras developers. Please support this effort, and help us save some time on server deployment.

**Comment by Matheus28** [comment]
The server side is unlikely to ever be open source. This package only exists to make deployment a bit easier from build bots (`npm install --global m28n-cli && m28n deploy`).
